<?php
		session_start();
		include("../conn/dataconnection.php");
		@$user_id=$_SESSION['user_id'];
		@$code=$_POST['code'];
		@$old_code=$_SESSION['Login_code'];
		@$realname=$_POST['realname'];
		@$sex=$_POST['sex'];
		@$email=$_POST['email'];
		@$user_tel=$_POST['user_tel'];
		if(!isset($code)||$code==''){
			@$sq_u=mysql_query("update user set realname='$realname',sex='$sex',email='$email',user_tel='$user_tel' where user_id='$user_id'");
			@$sq_num=mysql_affected_rows();
			if($sq_num>0){
				$response=array(
				"errno"=>0,
				"msg"=>'success',
				"data"=>true
				);
			}else{
			$response=array(
				"errno"=>1,
				"msg"=>'fail',
				"data"=>false
				);
			}
		}else{
			if($code!=$old_code){
			$response=array(
			"errno"=>2,
			"msg"=>'fail',
			"data"=>false
			);
			}else{
				@$sql=mysql_query("select * from user where user_tel='$user_tel'");
				@$sql_num=mysql_num_rows($sql);
				if($sql_num>0){//手机号码已经存在
					$response=array(
					"errno"=>3,
					"msg"=>'fail',
					"data"=>false
					);
				}else{
					@$sq_u=mysql_query("update user set realname='$realname',sex='$sex',email='$email',user_tel='$user_tel' where user_id='$user_id'");
					@$sq_num=mysql_affected_rows();
					if($sq_num>0){
						$response=array(
						"errno"=>4,
						"msg"=>'success',
						"data"=>true
						);
					}else{
						$response=array(
						"errno"=>5,
						"msg"=>'fail',
						"data"=>false
						);
					}
				}
			}
		}
echo json_encode($response);
								?>