<?php
include("../conn/dataconnection.php");
ob_end_clean();
$acct_yr=$_GET['acct_yr'];
$yu=$_GET['yu'];
$filename=$acct_yr."年".$yu."月份商品销售排行榜";  
header("Content-type:application/vnd.ms-excel");  
header("Content-Disposition:filename=".$filename.".xls");
@$sql=mysql_query("select * from good_sales where yr='$acct_yr' and mh='$yu' order by sales_amount desc");
$strexport="排名\t商品名称\t现售价(单位：元)\t成本价(单位：元)\t月销量\t月优惠(单位：元)\t月销售额(单位：元)\t月利润(单位：元)\t年度累计销量\t年度累计优惠(单位：元)\t年度累计销售额(单位：元)\t年度累计利润(单位：元)\t所属种类\r"; 
$i=0;
while(@$sql_g=mysql_fetch_array($sql)){
	@$good_id=$sql_g['good_id'];
	@$good=mysql_query("select * from goods where good_id='$good_id'");
	@$good_s=mysql_fetch_array($good);
	$i++;
	$strexport.=$i."\t";
	$strexport.=$good_s['good_name']."\t";
	$strexport.=$good_s['good_price']."\t";
	$strexport.=$good_s['buy_price']."\t";
	$strexport.=$sql_g['sales_amount']."\t";
	$strexport.=$sql_g['yuhui']."\t";
	$strexport.=$sql_g['sales_money']-$sql_g['yuhui']."\t";
	$strexport.=$sql_g['getreal_money']-$sql_g['yuhui']."\t";
	$all=mysql_query("select sum(sales_amount) from good_sales where yr='$acct_yr' and good_id='$good_id'");
	@$all1=mysql_fetch_array($all);
	$strexport.=$all1['sum(sales_amount)']."\t";
	@$all2=mysql_query("select sum(yuhui) from good_sales where yr='$acct_yr' and good_id='$good_id'");
	@$all2_1=mysql_fetch_array($all2);
	$strexport.=$all2_1['sum(yuhui)']."\t";
	@$all3=mysql_query("select sum(sales_money) from good_sales where yr='$acct_yr' and good_id='$good_id'");
	@$all3_1=mysql_fetch_array($all3);
	$strexport.=$all3_1['sum(sales_money)']-$all2_1['sum(yuhui)']."\t";
	@$all4=mysql_query("select sum(getreal_money) from good_sales where yr='$acct_yr' and good_id='$good_id'");
	@$all4_1=mysql_fetch_array($all4);
	$strexport.=$all4_1['sum(getreal_money)']-$all2_1['sum(yuhui)']."\t";
	@$kind_id=$good_s['kind_id'];
	$kind=mysql_query("select * from kind where kind_id='$kind_id'");
	@$kin=mysql_fetch_array($kind);
	@$strexport.=$kin['kind_name']."\r";
}
  $strexport.=$acct_yr."年"."$yu"."月份商品销售情况:"."\t";
  @$all_sales=mysql_query("select sum(sales_amount),sum(yuhui),sum(sales_money),sum(getreal_money) from good_sales where yr='$acct_yr' and mh='$yu'");
  @$all_sales1=mysql_fetch_array($all_sales);
  $strexport.="总销量:";
  @$strexport.=$all_sales1['sum(sales_amount)']."\t";
  $strexport.="总优惠:";
  $strexport.=$all_sales1['sum(yuhui)']."元\t";
  $strexport.="总销售额:";
  $strexport.=$all_sales1['sum(sales_money)']-$all_sales1['sum(yuhui)']."元\t";
  $strexport.="总利润:";
  $strexport.=$all_sales1['sum(getreal_money)']-$all_sales1['sum(yuhui)']."元\r";
  $year=mysql_query("select sum(sales_amount),sum(yuhui),sum(sales_money),sum(getreal_money) from good_sales where yr='$acct_yr'");
  $strexport.=$acct_yr."年商品销售情况:\t";
  $year1=mysql_fetch_array($year);
  $strexport.="总销量:";
  $strexport.=$year1['sum(sales_amount)']."\t";
  $strexport.="总优惠:";
  $strexport.=$year1['sum(yuhui)']."\t";
  $strexport.="总销售额:";
  $strexport.=$year1['sum(sales_money)']-$year1['sum(yuhui)']."\t";
  $strexport.="总利润:";
  $strexport.=$year1['sum(getreal_money)']-$year1['sum(yuhui)']."\r";
  $strexport=iconv('UTF-8',"GB2312//IGNORE",$strexport);  
  exit($strexport);  
?>